version: '3.2'

services:

  frontend:
    restart: always
    build: frontend
    ports:
      - 20080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - backend
    networks:
      - postgres-compose-network

  backend:
    restart: always
    build: backend
    ports:
      - 21080:80
    volumes:
      # Re-use local composer cache via host-volume
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      # Mount source-code for development
      - ./:/app
    depends_on:
      - pgsql
    networks:
      - postgres-compose-network

  pgsql:
    restart: always
    image: postgres:9.5
    ports:
    - 5432:5432
    environment:
      - POSTGRES_DB=yii2ecommerce
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    networks:
      - postgres-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "mmazoni.andrade@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "Admin2021!"
    ports:
      - "16543:80"
    depends_on:
      - pgsql
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge